# Generated by Django 5.0.14 on 2026-09-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('purchase_completed', 'Purchase completed'), ('sale_completed', 'Sale completed'), ('reconciliation_mismatch', 'Ledger reconciliation mismatch')], max_length=30),
        ),
    ]
